<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromArray;

class ErpOrderSampleExport implements FromArray
{
    use Exportable;

    public function array(): array
    {
        return [
            [
                '平台',
                '平台账号',
                '账号别名',
                '站点',
                '平台订单号',
                '下架类型',
                '订单类型',
                '付款时间',
                '发货时间',
                '审核时间(仓配)',
                '平台SKU',
                'ITEM_ID(ASIN)',
                '产品名称',
                'SKU',
                '一级品类',
                '二级品类',
                '发货仓库',
                '参考号',
                '运单号',
                '发货数量',
                '运输方式',
                '跟踪号',
                '产品重量',
                '订单原币种',
                '订单总金额(包含客户运费)(订单原币种)',
                '支付手续费(原币种)',
                '(ebay)成交费(原币种费用)',
                'fba费用(订单原币种)',
                '头程运费(订单原币种)',
                '头程关税(订单原币种)',
                '派送运费(订单原币种)',
                '其他费用(订单原币种)',
                '采购运费(订单原币种)',
                '采购成本(订单原币种)',
                '销项税(同步数据)(订单原币种)',
                '点击成交费(订单原币种)',
                '独家费用(订单原币种)',
                '国家',
                '客服备注',
                '毛利(原货币)',
                '毛利率%',
                '转换货币',
                '汇率',
                '订单总金额(包含客户运费)(HKD)',
                '支付手续费(HKD)',
                '(ebay)成交费(HKD)',
                'fba费用(HKD)',
                '头程运费(HKD)',
                '头程关税(HKD)',
                '派送运费(HKD)',
                '其他费用(HKD)',
                '采购运费(HKD)',
                '采购成本(HKD)',
                '销项税(同步数据)(HKD)',
                '点击成交费(HKD)',
                '独家费用(HKD)',
                '毛利(HKD)',
                '毛利率%',
                '单量统计辅助列'
            ],
            [
                'Platform',
                'Acc Nick Name',
                'Acc Name',
                'Site',
                'ERP Order ID',
                'Package Type',
                'Order Type',
                'Paid Date',
                'Shipped Date',
                'Audit Date',
                'Platform SKU',
                'ITEM_ID(ASIN)',
                'Product Name',
                'SKU',
                'Supplier Type',
                'Supplier',
                'Warehouse',
                'Site Order ID',
                'Package ID',
                'QTY',
                'Shipping Method',
                'Tracking',
                'Product Weight',
                'Original Currency',
                'Order Price (Original Currency)',
                'PayPal Fee (Original Currency)',
                'Transaction Fee (Original Currency)',
                'FBA Fee (Original Currency)',
                'First Mile Shipping Fee (Original Currency)',
                'First Mile Tariff (Original Currency)',
                'Last Mile Shipping Fee (Original Currency)',
                'Other Fee (Original Currency)',
                'Purchase Shipping Fee (Original Currency)',
                'Product Cost (Original Currency)',
                'Marketplace Tax (Original Currency)',
                'Cost of Point (Original Currency)',
                'Exclusives Referral Fee (Original Currency)',
                'Country',
                'Note',
                'Gross Profit (Original Currency)',
                'Gross Margin%',
                'HKD',
                'HKD Rate',
                'Order Price (HKD)',
                'PayPal Fee (HKD)',
                'Transaction Fee (HKD)',
                'FBA Fee (HKD)',
                'First Mile Shipping Fee (HKD)',
                'First Mile Tariff (HKD)',
                'Last Mile Shipping Fee (HKD)',
                'Other Fee (HKD)',
                'Purchase Shipping Fee (HKD)',
                'Product Cost (HKD)',
                'Marketplace Tax (HKD)',
                'Cost of Point (HKD)',
                'Exclusives Referral Fee (HKD)',
                'Gross Profit (HKD)',
                'Gross Margin%',
                'Order Quantity Statistics'
            ]
        ];
    }
}
